sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
language: node_js
node_js:
  - "8"
script:
  - npm run test
  - npm run build
deploy:
  provider: pages
  local-dir: dist
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
